# Generated by Django 3.1.3 on 2020-12-14 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20201214_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
